import {
  ChecklistPack,
  LoanItem,
  ServiceLogRecord,
  TaskReminder,
  TimelineEvent,
  VehicleTracker,
} from "./types";

export const INITIAL_VEHICLE_TRACKERS: VehicleTracker[] = [
  {
    id: "tire-rotation",
    title: "بالانس و جابه‌جایی تایرها",
    subtitle: "جابه‌جایی ضربدری جلو به عقب",
    category: "urgent",
    badgeText: "۲۰۰ کیلومتر عقب‌افتادگی",
    badgeType: "error",
    icon: "tire_repair",
    currentKm: 9800,
    targetKm: 10000,
    intervalKm: 10000,
    percentage: 102,
    scheduledAtKm: 85220,
    extraDetail: "زمان‌بندی‌شده در ۸۵٬۲۲۰ کیلومتر",
  },
  {
    id: "cabin-filter",
    title: "فیلتر کابین و تهویه",
    subtitle: "تمیزکاری فیلتر HEPA ضد حساسیت",
    category: "due-soon",
    badgeText: "۸۰۰ کیلومتر تا موعد",
    badgeType: "primary",
    icon: "air",
    currentKm: 4200,
    targetKm: 5000,
    intervalKm: 5000,
    percentage: 84,
    timeElapsedMonths: 5,
    timeTotalMonths: 6,
    targetDate: "~۱۹ آذر ۱۴۰۳",
    extraDetail: "تعویض بعدی: ~۱۹ آذر ۱۴۰۳",
  },
  {
    id: "brake-pads",
    title: "لنت و روغن ترمز",
    subtitle: "بررسی کالیپر و رطوبت روغن",
    category: "healthy",
    badgeText: "سالم (۴٬۵۸۰ کیلومتر مانده)",
    badgeType: "tertiary",
    icon: "disc_full",
    currentKm: 85420,
    targetKm: 90000,
    percentage: 48,
    extraDetail: "ضخامت لنت: ۸ میلی‌متر (نرمال)",
  },
  {
    id: "insurance-policy",
    title: "بیمه بدنه جامع",
    subtitle: "بیمه جامع #AL-9921",
    category: "policy",
    badgeText: "۳۴ روز",
    badgeType: "primary",
    icon: "security",
    targetDate: "۸ آذر ۱۴۰۳",
    extraDetail: "پرداخت خودکار فعال • سالانه $1,180.00",
    autoPay: true,
  },
];

export const INITIAL_SERVICE_LOGS: ServiceLogRecord[] = [
  {
    id: "log-1",
    title: "بازدید سالانه چندنقطه‌ای",
    date: "۲۲ شهریور ۱۴۰۳",
    provider: "نمایندگی تسلا",
    odometerKm: 81200,
    cost: 180.0,
    receiptVerified: true,
    notes: "سیستم تهویه ضدعفونی شد، پیچ‌های شاسی بررسی و ترمینال ۱۲ ولت تمیز شد.",
    category: "بازدید",
  },
  {
    id: "log-2",
    title: "تعویض تیغه برف‌پاک‌کن",
    date: "۱۵ خرداد ۱۴۰۳",
    provider: "سرویس شخصی",
    odometerKm: 76900,
    cost: 45.0,
    receiptVerified: false,
    notes: "تیغه‌های Bosch Aerotwin نصب شد.",
    category: "قطعات",
  },
  {
    id: "log-3",
    title: "روغن ترمز و دیاگ سنسور",
    date: "۲۹ بهمن ۱۴۰۲",
    provider: "اتواسپا اسپارکل",
    odometerKm: 71400,
    cost: 115.0,
    receiptVerified: true,
    notes: "تست رطوبت روغن DOT4 قبول شد (۰٫۸٪).",
    category: "ترمز",
  },
  {
    id: "log-4",
    title: "تعویض فیلتر کابین HEPA",
    date: "۲۰ دی ۱۴۰۲",
    provider: "نمایندگی تسلا",
    odometerKm: 68000,
    cost: 120.0,
    receiptVerified: true,
    notes: "هر دو فیلتر ورودی داخلی تعویض شد.",
    category: "تهویه",
  },
  {
    id: "log-5",
    title: "جابه‌جایی و بالانس تایر",
    date: "۱ آذر ۱۴۰۲",
    provider: "تایر کو",
    odometerKm: 65200,
    cost: 90.0,
    receiptVerified: true,
    notes: "عمق آج ۷٫۲ میلی‌متر، سایش یکنواخت.",
    category: "تایر",
  },
  {
    id: "log-6",
    title: "دیاگ باتری کمکی ۱۲ ولت",
    date: "۲۳ مرداد ۱۴۰۲",
    provider: "امداد سیار تسلا",
    odometerKm: 58100,
    cost: 90.0,
    receiptVerified: true,
    notes: "باتری لیتیومی ۱۲ ولت در سلامت کامل.",
    category: "برق",
  },
];

export const INITIAL_LOANS: LoanItem[] = [
  {
    id: "loan-1",
    title: "وام مسکن آپارتمان",
    bank: "Chase Bank",
    icon: "home",
    dueNotice: "۳ روز مانده (۵ آبان)",
    dueDate: "۵ آبان",
    monthlyAmount: 750.0,
    remainingAmount: 24500.0,
    totalAmount: 38000.0,
    paidInstallments: 38,
    totalInstallments: 120,
    progressPercent: 31.6,
    linkedAccount: "Chase Premier •••• 4821",
    autoPay: true,
    category: "mortgage",
    paidThisCycle: false,
  },
  {
    id: "loan-2",
    title: "وام خودرو تسلا",
    bank: "Ally Auto",
    icon: "directions_car",
    dueNotice: "۱۱ روز مانده (۱۳ آبان)",
    dueDate: "۱۳ آبان",
    monthlyAmount: 380.0,
    remainingAmount: 8360.0,
    totalAmount: 18240.0,
    paidInstallments: 26,
    totalInstallments: 48,
    progressPercent: 54.2,
    autoPay: false,
    category: "auto",
    paidThisCycle: false,
  },
  {
    id: "loan-3",
    title: "مک‌بوک پرو (بدون بهره)",
    bank: "Apple Card",
    icon: "laptop_mac",
    dueNotice: "۲ ماه مانده!",
    dueDate: "۲۴ آبان",
    monthlyAmount: 150.0,
    remainingAmount: 300.0,
    totalAmount: 1800.0,
    paidInstallments: 10,
    totalInstallments: 12,
    progressPercent: 83.3,
    autoPay: true,
    category: "hardware",
    paidThisCycle: false,
    badgeText: "۲ ماه مانده!",
    badgeType: "tertiary",
  },
];

export const INITIAL_REMINDERS: TaskReminder[] = [
  {
    id: "task-1",
    title: "ثبت ادعای بیمه درمانی سه‌ماهه سوم",
    dueTime: "امروز ساعت ۱۴:۰۰",
    dueDateCategory: "today",
    priority: "high",
    category: "work",
    source: "پرتال بیمه",
    done: false,
  },
  {
    id: "task-2",
    title: "تحویل نسخه فشار خون (داروخانه)",
    dueTime: "امروز ساعت ۱۷:۳۰",
    dueDateCategory: "today",
    category: "health",
    location: "داروخانه • نسخه #884920",
    recurring: "ماهانه",
    done: false,
  },
  {
    id: "task-3",
    title: "زمان‌بندی بازدید سالانه تهویه",
    dueTime: "فردا ساعت ۱۰:۰۰",
    dueDateCategory: "tomorrow",
    category: "home",
    location: "سرویس سالانه (گارانتی)",
    done: false,
  },
  {
    id: "task-4",
    title: "ثبت ارزیابی مالیاتی فصلی ملک",
    dueTime: "۲۰ آبان، ساعت ۱۷:۰۰",
    dueDateCategory: "upcoming",
    category: "finance",
    location: "پرتال الکترونیک",
    done: false,
  },
  {
    id: "task-5",
    title: "جرم‌گیری و فلوراید سالانه دندان",
    dueTime: "۱۴ آبان، ساعت ۱۰:۰۰",
    dueDateCategory: "upcoming",
    category: "health",
    location: "کلینیک دکتر هریس",
    done: false,
  },
];

export const INITIAL_CHECKLISTS: ChecklistPack[] = [
  {
    id: "camping-pack",
    title: "کمپ آخر هفته و سفر جاده‌ای",
    subtitle: "قالب‌های آماده سبک زندگی و سفر",
    icon: "forest",
    active: true,
    items: [
      { id: "c1", text: "بررسی باد تایر و مایع شیشه‌شور", completed: true },
      { id: "c2", text: "جعبه کمک‌های اولیه و چراغ‌قوه", completed: true },
      { id: "c3", text: "اجاق سفری و کپسول سوخت", completed: true },
      { id: "c4", text: "کلمن و یخ‌پک عایق", completed: true },
      { id: "c5", text: "فیلتر تصفیه آب و قمقمه", completed: true },
      { id: "c6", text: "پتوی اضطراری و چاقوی چندکاره", completed: true },
      { id: "c7", text: "میله چادر و کیسه خواب", completed: false },
      { id: "c8", text: "دانلود نقشه آفلاین GPS", completed: false },
      { id: "c9", text: "اسپری حشره و ضدآفتاب ۵۰+", completed: false },
    ],
  },
  {
    id: "groceries-pack",
    title: "خرید هفتگی سالم",
    subtitle: "۱۲ قلم • آخرین تکمیل یکشنبه",
    icon: "shopping_cart",
    active: false,
    items: [
      { id: "g1", text: "شیر بادام ارگانیک", completed: true },
      { id: "g2", text: "اسفناج و کلم", completed: true },
      { id: "g3", text: "فیله سالمون", completed: false },
      { id: "g4", text: "ماست یونانی ساده (بدون قند)", completed: false },
      { id: "g5", text: "آووکادو (بسته ۴تایی)", completed: true },
      { id: "g6", text: "جو دوسر", completed: false },
      { id: "g7", text: "روغن زیتون فرابکر", completed: false },
      { id: "g8", text: "تخم‌مرغ ارگانیک", completed: true },
    ],
  },
  {
    id: "travel-pack",
    title: "ملزومات سفر خارجی",
    subtitle: "۱۸ قلم (گذرنامه، مبدل، ویزا)",
    icon: "flight_takeoff",
    active: false,
    items: [
      { id: "t1", text: "گذرنامه (اعتبار بیش از ۶ ماه)", completed: true },
      { id: "t2", text: "مبدل برق بین‌المللی", completed: true },
      { id: "t3", text: "داروهای تجویزی در بسته اصلی", completed: false },
      { id: "t4", text: "هدفون بی‌سیم نویزکنسلینگ", completed: false },
      { id: "t5", text: "کارت بیمه سفر و درمان", completed: false },
      { id: "t6", text: "کارت اعتباری پشتیبان بدون کارمزد", completed: true },
    ],
  },
];

export const INITIAL_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: "tl-1",
    title: "نوبت پزشک",
    timeLabel: "امروز، ساعت ۱۴:۳۰",
    dateBadge: "امروز",
    category: "health",
    categoryLabel: "سلامت",
    subtitle: "کلینیک دکتر هریس • اتاق ۴۰۲",
    icon: "medical_services",
  },
  {
    id: "tl-2",
    title: "کارواش و دیتیلینگ",
    timeLabel: "فردا، ساعت ۹:۰۰",
    dateBadge: "فردا",
    category: "auto",
    categoryLabel: "خودرو",
    subtitle: "اتواسپا اسپارکل (رزرو شده)",
    icon: "local_car_wash",
  },
  {
    id: "tl-3",
    title: "قسط وام مسکن",
    timeLabel: "۵ آبان ۱۴۰۳",
    dateBadge: "۵ آبان",
    category: "finance",
    categoryLabel: "مالی",
    subtitle: "$1,420.00 • برداشت خودکار",
    icon: "credit_card",
  },
  {
    id: "tl-4",
    title: "بستن چمدان سفر",
    timeLabel: "۷ آبان ۱۴۰۳",
    dateBadge: "۷ آبان",
    category: "travel",
    categoryLabel: "سفر",
    subtitle: "پیشرفت چک‌لیست: ۶ از ۹",
    icon: "luggage",
  },
];

export const ASSETS = {
  logo: "https://lh3.googleusercontent.com/aida/AEtjO1W-EJqwLhY3Iu5KFI_JCB0ldblJfH8pTO_f-P9-KSYYHoXSwbw6fx5SF7NsohsQ5GvGSiucYsMrWXtGbwXpKm2aZIWmle9BLFpew_YH8h5GfmU9tev7HJK-J0uloP_6fmQk2ByqPmol3KemExqAavfm7vjZhhDnqawNrgkSbQULXUV7yqtdiIA4IjDVqt7JPtrFzocJbVzWEWZJrZBo76pQMr4QiGlUcNg3dDUsdNqFeT7u9vSHxdzCWJs",
  avatar:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuC45Mg_hIVqDWASmlBXitw7KqR-YjLPEk8xZ8ogSC2qyvL1o_mRrKKimN1XOtUT3HwsrxJtjzOP_FD0YqGtTaQoPqZ8xzGReX53CgEUrHlSebY0a3ABG6RBB-CKdQa8j9_eKVFK__I72gpRSd3WO8HFEm0f5SiTz3Mw8KO30d5WHLqIGDkhx07AW8UpMTFxhRmd9n0y1O8crh3M5PhRAbVuBI0yg1yMwYrzga8Z6WxAfNvKmXQXKetp",
  evGarage:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuChoOnYg4T3RkxCLGdngCef-ZcEZxFy02bXkp1TmcGPQQSsbSYCnAGSKGgTCs44UeWHLtPM2qYarlIWWmgNkkkVhF5bzsF7dxKKypEstDKzx0VVDjJ9pxxE9nEpCRDs1Z_xLSg1neohsUFmSjXDJROLa4D3D9kRCJ01xlhjic_c6DXb-pCiqVzeNHtvXsnh-bBdcD8XbacLEMeddyB7BJH7v9FcaikJsiCvqcqtYRiAjlbQ8tt6pyN9",
  teslaModel3:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuDKU9sGvbYDNM_8UkLFMqh9WMBnUOLqhXL1x26Yqp1M5KD4XIfH5JNw6CG6U7VZSaiJEsBCITVoIIiQWYkgPLF22buNlyVYr5QQz77yT2Q-Pd69UpcYyrIu0aXciT22OH0z6pdkLeVoLfUWIeVQ5WMfYukreS7FHuMBKWQKwoE1_x7kD7OZXP21FA8iniQ0HyFLyxBqJ2-FB4nSxrTyCqtSLFEgmF_wMCsnkXSIAKDSZOSHEU-CiT6U",
};

export const ROUTE_TITLES: Record<string, string> = {
  "/": "داشبورد",
  "/vehicles": "خودروها",
  "/loans": "وام‌ها و اقساط",
  "/tasks": "کارها و لیست‌ها",
};
