"use client";

import type { LucideIcon } from "lucide-react";
import {
  AlarmClock,
  ArrowLeft,
  BadgeCheck,
  BatteryCharging,
  Bell,
  BellRing,
  Building2,
  Calendar,
  CalendarDays,
  Car,
  CarFront,
  Check,
  ChevronLeft,
  Circle,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  ClipboardCheck,
  Clock,
  CloudRain,
  CreditCard,
  Disc3,
  Download,
  Droplet,
  Droplets,
  FileSearch,
  Flame,
  Fuel,
  Gauge,
  History,
  House,
  ImagePlus,
  Info,
  Landmark,
  Laptop,
  LayoutDashboard,
  LifeBuoy,
  ListChecks,
  ListPlus,
  Luggage,
  MapPin,
  Pencil,
  PlaneTakeoff,
  Plus,
  ReceiptText,
  RefreshCw,
  Repeat,
  RotateCcw,
  Search,
  Settings,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Stethoscope,
  Trash2,
  TreePine,
  TriangleAlert,
  Wallet,
  Wind,
  Wrench,
  CircleX,
  X,
  Zap,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  add: Plus,
  add_a_photo: ImagePlus,
  add_circle: CirclePlus,
  add_task: ListPlus,
  air: Wind,
  alarm: AlarmClock,
  apartment: Building2,
  arrow_forward: ArrowLeft,
  auto_awesome: Sparkles,
  autorenew: RefreshCw,
  battery_charging_full: BatteryCharging,
  bolt: Zap,
  build_circle: Wrench,
  cached: History,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  check: Check,
  check_circle: CircleCheck,
  checklist: ListChecks,
  chevron_right: ChevronLeft,
  close: X,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  delete: Trash2,
  directions_car: Car,
  disc_full: Disc3,
  download: Download,
  edit: Pencil,
  electric_car: CarFront,
  error: CircleX,
  event_repeat: Repeat,
  fact_check: ClipboardCheck,
  flight_takeoff: PlaneTakeoff,
  forest: TreePine,
  home: House,
  info: Info,
  laptop_mac: Laptop,
  local_car_wash: Droplets,
  local_fire_department: Flame,
  location_on: MapPin,
  luggage: Luggage,
  manage_search: FileSearch,
  medical_services: Stethoscope,
  notifications: Bell,
  notifications_active: BellRing,
  oil_barrel: Fuel,
  radio_button_unchecked: Circle,
  receipt_long: ReceiptText,
  restart_alt: RotateCcw,
  schedule: Clock,
  search: Search,
  security: ShieldCheck,
  settings: Settings,
  shopping_cart: ShoppingCart,
  speed: Gauge,
  sync: RefreshCw,
  task_alt: CircleCheck,
  tire_repair: LifeBuoy,
  tune: SlidersHorizontal,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  warning: TriangleAlert,
  water_drop: Droplet,
  wiper: CloudRain,
};

interface IProps {
  name: string;
  className?: string;
  filled?: boolean;
}

export function AppIcon({ name, className, filled = false }: IProps) {
  const Icon = ICON_MAP[name] ?? CircleHelp;
  return (
    <Icon
      className={className}
      fill={filled ? "currentColor" : "none"}
      aria-hidden="true"
    />
  );
}
